## The independent distribution

Reinterpreting the batch shapes as event shapes.

In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt
import tensorflow_probability as tfp
tfd = tfp.distributions

<tf.Tensor: shape=(), dtype=float32, numpy=-2.9388978>

In the following cell we can see a multivariate normal distribution, with `batch_shape=[] event_shape=[2]`

In [4]:
mv_normal = tfd.MultivariateNormalDiag(loc = [-1, 0.5], scale_diag = [1., 1.5])
mv_normal.log_prob([-0.2, 1.8])

<tf.Tensor: shape=(), dtype=float32, numpy=-2.9388978>

The return of log_prob is an scalar (`shape=()`).

On the other hand we have a batched normal, with ` batch_shape=[2] event_shape=[]` 

In [7]:
batched_normal = tfd.Normal(loc = [-1., 0.5], scale = [1., 1.5])   # Events are single variables, we have two different normal distributions
batched_normal.log_prob([-0.2, 1.8])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.2389386, -1.699959 ], dtype=float32)>

The return of `log_prob` is of `shape=(2,)` because we have two different log probs.

#### The independent distribution

We can use the `Independent` distribution to transform our batched normal distribution so that is equivalent to the Multivariate normal diag distribution:

In [11]:
batched_normal

<tfp.distributions.Normal 'Normal' batch_shape=[2] event_shape=[] dtype=float32>

In [12]:
independent_normal = tfd.Independent(batched_normal, reinterpreted_batch_ndims = 1)   # How many dimensions should be 'absorbed' to the event space
independent_normal

<tfp.distributions.Independent 'IndependentNormal' batch_shape=[] event_shape=[2] dtype=float32>

In [13]:
independent_normal.log_prob([-0.2, 1.8])

<tf.Tensor: shape=(), dtype=float32, numpy=-2.9388976>

The `independent_normal` is now equivalent to our multivariate normal diag distribution

**A higher dimension example**

In [14]:
batched_normal = tfd.Normal(
    loc=[[-1.,0.5], [0.,1.], [0.3,-0.1]],
    scale=[[1.,1.5], [0.2, 0.8], [2.,1.]])

batched_normal

<tfp.distributions.Normal 'Normal' batch_shape=[3, 2] event_shape=[] dtype=float32>

In [15]:
independent_normal = tfd.Independent(batched_normal, reinterpreted_batch_ndims = 1)
independent_normal

<tfp.distributions.Independent 'IndependentNormal' batch_shape=[3] event_shape=[2] dtype=float32>

In [16]:
independent_normal = tfd.Independent(batched_normal, reinterpreted_batch_ndims = 2)
independent_normal

<tfp.distributions.Independent 'IndependentNormal' batch_shape=[] event_shape=[3, 2] dtype=float32>

The default for `reinterpreted_batch_ndims` is None, ant it takes all the arguments minus 1 of the `batch_shape` to the `event_shape`