In [7]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

In [8]:
exp = tfd.Exponential(rate = [[1., 1.5, 0.8],[0.3, 0.4, 1.8]])
exp

<tfp.distributions.Exponential 'Exponential' batch_shape=[2, 3] event_shape=[] dtype=float32>

In [11]:
ind_exp = tfd.Independent(exp, reinterpreted_batch_ndims = 1)
ind_exp.sample(4)

<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[0.06378616, 1.1543711 , 0.38331285],
        [1.5103008 , 1.0657685 , 1.3842641 ]],

       [[0.32274973, 0.50812453, 0.3622837 ],
        [1.5724745 , 1.2363564 , 0.30070743]],

       [[0.28364933, 0.17686133, 0.04853925],
        [5.6652737 , 0.05536039, 0.4604963 ]],

       [[2.6862254 , 0.6901496 , 2.2046735 ],
        [2.673191  , 0.39295867, 0.03938442]]], dtype=float32)>

In [12]:
ind_exp.sample(4).shape

TensorShape([4, 2, 3])

More complex example:

In [13]:
rates = [
    [[[1., 1.5, 0.8], [0.3,0.4,1.8]]],
    [[[0.2, 0.4, 1.4], [0.4, 1.1, 0.9]]]
]

In [15]:
exp = tfd.Exponential(rate = rates)  
exp

<tfp.distributions.Exponential 'Exponential' batch_shape=[2, 1, 2, 3] event_shape=[] dtype=float32>

In [19]:
ind_exp = tfd.Independent(exp, reinterpreted_batch_ndims = 2)
ind_exp

<tfp.distributions.Independent 'IndependentExponential' batch_shape=[2, 1] event_shape=[2, 3] dtype=float32>

In [22]:
ind_exp.sample([4,2])

ind_exp.sample([4,2]).shape

TensorShape([4, 2, 2, 1, 2, 3])

In [23]:
ind_exp.log_prob(0.5)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-4.2501554],
       [-5.3155975]], dtype=float32)>

In [25]:
ind_exp.log_prob([0.3, 0.5, 0.8])  # broadcastable to (2,1,2,3)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-4.7701554],
       [-5.885597 ]], dtype=float32)>

In [27]:
ind_exp.log_prob(tf.random.uniform((5,1,1,2,1)))  # broadcastable to (2,1,2,3)

ind_exp.log_prob(tf.random.uniform((5,1,1,2,1))).shape

TensorShape([5, 2, 1])